"""empty message

Revision ID: 718745742640
Revises: 773a07ef91e5
Create Date: 2022-08-16 20:41:27.879560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '718745742640'
down_revision = '773a07ef91e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('planet_ibfk_1', 'planet', type_='foreignkey')
    op.drop_column('planet', 'user_id')
    op.drop_constraint('vehicle_ibfk_1', 'vehicle', type_='foreignkey')
    op.drop_column('vehicle', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('vehicle_ibfk_1', 'vehicle', 'user', ['user_id'], ['id'])
    op.add_column('planet', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('planet_ibfk_1', 'planet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
