"""empty message

Revision ID: 773a07ef91e5
Revises: 2ba6dc74ff68
Create Date: 2022-08-16 20:25:53.115172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '773a07ef91e5'
down_revision = '2ba6dc74ff68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('character_ibfk_2', 'character', type_='foreignkey')
    op.drop_column('character', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('character_ibfk_2', 'character', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
